# Launch the ShinyApp (Do not remove this comment)
# To deploy, run: rsconnect::deployApp()
# Or use the blue button on top of this file
# print('Rare FMA')
# dir.create('~/.fonts')
# file.copy(system.file('app/www/Arial Narrow.ttf', package = "rarefma"), "~/.fonts")
# file.copy(system.file('app/www/Arial Narrow Bold Italic.ttf', package = "rarefma"), "~/.fonts")
# file.copy(system.file('app/www/Arial Narrow Bold.ttf', package = "rarefma"), "~/.fonts")
# file.copy(system.file('app/www/Arial Narrow Italic.ttf', package = "rarefma"), "~/.fonts")
# system('fc-cache -f ~/.fonts')
pkgload::load_all(export_all = FALSE, helpers = FALSE, attach_testthat = FALSE)
options( "golem.app.prod" = TRUE)
rarefma::run_app()