PLOT_HEIGHT <- 625
PLOT_WIDTH <- 1000
STATIC_TABLE_HEIGHT <- 800
SPINNER_COLOR <- "#004794"
TABLE_ROW_COLOR <- "#cee9f0"
MIN_DATA_ROWS <- 0
NO_TREND_ATTEMP <- NULL
FACET_WARNING <- "FACET_WARNING"
HISTORICAL_WARNING <- "HISTORICAL_WARNING"
FAIL_TREND <- "FAIL_TREND"
NO_PLOT_ATTEMP <- NULL
CURRENT_YEAR <- lubridate::year(lubridate::now())
WATERMARK_LABEL <- paste("Fish Forever (", CURRENT_YEAR, "). Rare.", sep="")